server:
  port: 8088
mybatis:
  mapper-locations: classpath:mapper/*.xml
spring:
  application:
    name: cla-service
  datasource:
    url: jdbc:mysql://localhost:3306/dm
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka